---
title: "CBCL face image"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,collapes = TRUE,message = FALSE)
```

# Load the 2429 images, transform to vector and comnbine as a matrix V.

```{r}
rm(list=ls())
library(pixmap)
# Load the first image and transform it into a vector.
CBCL_imag <- read.pnm(file = "C:/UCD/master/3/data/CBCL/face/face00001.pgm")
plot(CBCL_imag)
#Get the pixel intensity of the image.
CBCL_mat <- CBCL_imag@grey
#Convert to vector
V_CBCL_1 <- as.vector (CBCL_mat)

#Load the rest images and construct the matrix V.
for(i in 2:2429){
  #Get the format that the image files are named. e.g. Transform 1 to 00001, 110 to 00110.
  i <- formatC(i, width = 5, flag = 0)
  path <- paste("C:/UCD/master/3/data/CBCL/face/face", i, ".pgm", sep = "")
  imag <- read.pnm(file = path)
  
  #Get the pixel intensity.
  imag_mat <- imag@grey
  #Transform to vector
  imag_vec <- as.vector(imag_mat)
  #Combine in columns to construct V.
  V_CBCL <- cbind(V_CBCL_1, imag_vec)
  V_CBCL_1 <- V_CBCL
}

#Select 9 original images to print out.
sel = c(1,51,121,131,151,161,571,1845,2378)
for(i in sel){
  i <- formatC(i, width = 5, flag = 0)
  path <- paste("C:/UCD/master/3/data/CBCL/face/face", i, ".pgm", sep = "")
  imag <- read.pnm(file = path)
  plot(imag, axes = FALSE)
}
```

#Run NMF using NMF package and the first cost function.

```{r}
library(NMF)
library(imager)

#Run NMF
CBCL_model <- nmf(V_CBCL, rank = 49, method = "Lee", seed = 1234)
CBCL_W = CBCL_model@fit@W
V_appr_CBCL = fitted(CBCL_model)

#Transform the columns of W into matrix and convert to image to get the basic images.
for(i in 1:49){
  appr_mat = matrix(CBCL_W[,i], nrow = 19, ncol = 19)
  #Reverse white and black.
  plot(as.cimg(t(1-appr_mat)), axes = FALSE)
}


#Print out the NMF approximation of the selected 9 images.
for(i in sel){
  mat = matrix(V_appr_CBCL[,i], nrow = 19, ncol = 19)
  plot(as.cimg(mat), axes = FALSE)
}
```

#Run NMF using the first cost function and without using the NMF package.

```{r}
# Explanation of the input data:
# V is the matrix that will be factorized
# R is the rank of NMF
# iter is the maximum number of iterations
# err is a small value set as a condition to stop the iteration.
# If the square of the Euclidian distance of the W%*%H in the kth iteration and the W%*%H in the (k+1)th iteration is smaller than err, then the iteration can be stopped. 
NMF_1.function = function(V,R,iter,err){
  N = nrow(V)
  M = ncol(V)
  
  # Initialise W and H. The initial entricies of W and H is randomly chosen between 0 and the maximum entry of V.
  W = matrix(runif(N*R, min=0, max=max(V)), nrow=N)#Aviod for loops to improve calculation speed.
  H = matrix(runif(R*M, min=0, max=max(V)), nrow=R)#Aviod for loops to improve calculation speed.
  
  W_1=W
  H_1=H
  # Use the update rules for the first cost function to update W and H iteratively.
  for (k in 1:iter){
    A=V%*%t(H_1)
    B=W_1%*%H_1%*%t(H_1)
    C=t(W_1)%*%V
    D=t(W_1)%*%W_1%*%H_1
    for (n in 1:N){
      for (r in 1:R){
        W[n,r] = W_1[n,r]*A[n,r]/B[n,r]
      }
    }
    
    for (r in 1:R){
      for (m in 1:M){
        H[r,m] = H_1[r,m]*C[r,m]/D[r,m]
      }
    }
    # Calculate the change between 2 iterations.
    E=W%*%H-W_1%*%H_1
    W_1=W
    H_1=H
    
    # Stop the iteration if the distance between 2 iterations is smaller than err.
    distance=sum(E^2)
    if (distance<err){
      break
    }
  }
  
  # Return W and H.
  output=list(a=W,b=H)
  return(output)
}

#Using the NMF_1.function to run NMF.
outcome_1=NMF_1.function(V_CBCL,49,5000,0.01)
# Get W and H.
W_image=outcome_1$a
H_image=outcome_1$b
# Get NMF approximation.
V_nmf=W_image%*%H_image

#Transform the columns of W into matrix and convert to image to get the basic images.
for(i in 1:49){
  appr_mat = matrix(W_image[,i], nrow = 19, ncol = 19)
  #Reverse white and black.
  plot(as.cimg(t(1-appr_mat)), axes = FALSE)
}

#Print out the NMF approximation of the selected 9 images.
for(i in sel){
  mat = matrix(V_nmf[,i], nrow = 19, ncol = 19)
  plot(as.cimg(mat), axes = FALSE)
}
```

#Run NMF using NMF package and the second cost function.

```{r}
#Run NMF
CBCL_model <- nmf(V_CBCL, rank = 49, method = "Brunet", seed = 1234)
CBCL_W = CBCL_model@fit@W
V_appr_CBCL = fitted(CBCL_model)

#Transform the columns of W into matrix and convert to image to get the basic images.
for(i in 1:49){
  appr_mat = matrix(CBCL_W[,i], nrow = 19, ncol = 19)
  #Reverse white and black.
  plot(as.cimg(t(1-appr_mat)), axes = FALSE)
}


#Print out the NMF approximation of the selected 9 images.
for(i in sel){
  mat = matrix(V_appr_CBCL[,i], nrow = 19, ncol = 19)
  plot(as.cimg(mat), axes = FALSE)
}
```

#Run NMF using the second cost function and without using the NMF package.

```{r}
# Explanation of the input data:
# V is the matrix that will be factorized
# R is the rank of NMF
# iter is the maximum number of iterations
# err is a small value set as a condition to stop the iteration.
# If the square of the Euclidian distance of the W%*%H in the kth iteration and the W%*%H in the (k+1)th iteration is smaller than err, then the iteration can be stopped. 
NMF_2.function = function(V,R,iter,err){
  N = nrow(V)
  M = ncol(V)
  
  # Initialise W and H. The initial entricies of W and H is randomly chosen between 0 and the maximum entry of V.
  W = matrix(runif(N*R, min=0, max=max(V)), nrow=N)#Aviod for loops to improve calculation speed.
  H = matrix(runif(R*M, min=0, max=max(V)), nrow=R)#Aviod for loops to improve calculation speed.
 
  W_1=W
  H_1=H
  # Use the update rules for the second cost function to update W and H iteratively.
  for (k in 1:iter){
    A=W%*%H
  
    for (n in 1:N){
      for (r in 1:R){
        H_V = H[r,]*V[n,]/A[n,]
        W[n,r] = W_1[n,r]*sum(H_V)/sum(H[r,])
      }
    }
    
    for (r in 1:R){
      for (m in 1:M){
        W_V = W[,r]*V[,m]/A[,m]
        H[r,m] = H_1[r,m]*sum(W_V)/sum(W[,r])
      }
    }
    # Calculate the change between 2 iterations.
    E=W%*%H-W_1%*%H_1
    W_1=W
    H_1=H
    
    # Stop the iteration if the distance between 2 iterations is smaller than err.
    distance=sum(E^2)
    if (distance<err){
      break
    }
  }
  output=list(a=W,b=H)
  return(output)
}

#Using the NMF_1.function to run NMF.
outcome_2=NMF_2.function(V_CBCL,49,5000,0.01)
# Get W and H.
W_image=outcome_2$a
H_image=outcome_2$b
# Get NMF approximation.
V_nmf=W_image%*%H_image

#Transform the columns of W into matrix and convert to image to get the basic images.
for(i in 1:49){
  appr_mat = matrix(W_image[,i], nrow = 19, ncol = 19)
  #Reverse white and black.
  plot(as.cimg(t(1-appr_mat)), axes = FALSE)
}

#Print out the NMF approximation of the selected 9 images.
for(i in sel){
  mat = matrix(V_nmf[,i], nrow = 19, ncol = 19)
  plot(as.cimg(mat), axes = FALSE)
}
```

