---
title: "image compression without using the NMF package"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,collapes = TRUE,message = FALSE)
```

# Load the image and print out the original image.

```{r}
rm(list=ls())
library(NMF)
library(imager)
rgb_image <- load.image("https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Raffaello_Sanzio_-_Madonna_del_Cardellino_-_Google_Art_Project.jpg/549px-Raffaello_Sanzio_-_Madonna_del_Cardellino_-_Google_Art_Project.jpg")
plot(rgb_image, axes = FALSE)
```

# Convert the image into a gray-scale format, which reduces its spectrum to a single channel.

```{r}
gray_image <- grayscale(rgb_image)
plot(gray_image, axes = FALSE)

# Convert the grayscaled image into a matrix
gray_image_mat <- as.matrix(gray_image)
```

# Set up a function to run NMF based on the first cost function.

```{r}
# Explanation of the input data:
# V is the matrix that will be factorized
# R is the rank of NMF
# iter is the maximum number of iterations
# err is a small value set as a condition to stop the iteration.
# If the square of the Euclidian distance of the W%*%H in the kth iteration and the W%*%H in the (k+1)th iteration is smaller than err, then the iteration can be stopped. 
NMF_1.function = function(V,R,iter,err){
  N = nrow(V)
  M = ncol(V)
  
  # Initialise W and H. The initial entricies of W and H is randomly chosen between 0 and the maximum entry of V.
  W = matrix(runif(N*R, min=0, max=max(V)), nrow=N)#Aviod for loops to improve calculation speed.
  H = matrix(runif(R*M, min=0, max=max(V)), nrow=R)#Aviod for loops to improve calculation speed.
  
  W_1=W
  H_1=H
  # Use the update rules for the first cost function to update W and H iteratively.
  for (k in 1:iter){
    A=V%*%t(H_1)
    B=W_1%*%H_1%*%t(H_1)
    C=t(W_1)%*%V
    D=t(W_1)%*%W_1%*%H_1
    for (n in 1:N){
      for (r in 1:R){
        W[n,r] = W_1[n,r]*A[n,r]/B[n,r]
      }
    }
    
    for (r in 1:R){
      for (m in 1:M){
        H[r,m] = H_1[r,m]*C[r,m]/D[r,m]
      }
    }
    # Calculate the change between 2 iterations.
    E=W%*%H-W_1%*%H_1
    W_1=W
    H_1=H
    
    # Stop the iteration if the distance between 2 iterations is smaller than err.
    distance=sum(E^2)
    if (distance<err){
      break
    }
  }
  
  # Return W and H.
  output=list(a=W,b=H)
  return(output)
}
```

# Run NMF when R=20, 40, 80, 160 using the first cost function

```{r}
# Run NMF (R=20)
outcome_1=NMF_1.function(gray_image_mat,20,5000,0.01)
# Get W and H.
W_image=outcome_1$a
H_image=outcome_1$b
# Get NMF approximation and transform to image.
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)

# Run NMF (R=40)
outcome_2=NMF_1.function(gray_image_mat,40,5000,0.01)
# Get W and H.
W_image=outcome_2$a
H_image=outcome_2$b
# Get NMF approximation and transform to image.
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)

# Run NMF (R=80)
outcome_3=NMF_1.function(gray_image_mat,80,5000,0.01)
# Get W and H.
W_image=outcome_3$a
H_image=outcome_3$b
# Get NMF approximation and transform to image.
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)

# Run NMF (R=160)
outcome_4=NMF_1.function(gray_image_mat,160,5000,0.01)
# Get W and H.
W_image=outcome_4$a
H_image=outcome_4$b
# Get NMF approximation and transform to image.
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)
```

# Set up a function to run NMF based on the second cost function.

```{r}
# Explanation of the input data:
# V is the matrix that will be factorized
# R is the rank of NMF
# iter is the maximum number of iterations
# err is a small value set as a condition to stop the iteration.
# If the square of the Euclidian distance of the W%*%H in the kth iteration and the W%*%H in the (k+1)th iteration is smaller than err, then the iteration can be stopped. 
NMF_2.function = function(V,R,iter,err){
  N = nrow(V)
  M = ncol(V)
  
  # Initialise W and H. The initial entricies of W and H is randomly chosen between 0 and the maximum entry of V.
  W = matrix(runif(N*R, min=0, max=max(V)), nrow=N)#Aviod for loops to improve calculation speed.
  H = matrix(runif(R*M, min=0, max=max(V)), nrow=R)#Aviod for loops to improve calculation speed.
 
  W_1=W
  H_1=H
  # Use the update rules for the second cost function to update W and H iteratively.
  for (k in 1:iter){
    A=W%*%H
  
    for (n in 1:N){
      for (r in 1:R){
        H_V = H[r,]*V[n,]/A[n,]
        W[n,r] = W_1[n,r]*sum(H_V)/sum(H[r,])
      }
    }
    
    for (r in 1:R){
      for (m in 1:M){
        W_V = W[,r]*V[,m]/A[,m]
        H[r,m] = H_1[r,m]*sum(W_V)/sum(W[,r])
      }
    }
    # Calculate the change between 2 iterations.
    E=W%*%H-W_1%*%H_1
    W_1=W
    H_1=H
    
    # Stop the iteration if the distance between 2 iterations is smaller than err.
    distance=sum(E^2)
    if (distance<err){
      break
    }
  }
  output=list(a=W,b=H)
  return(output)
}
```

# Run NMF when R=20, 40, 80, 160 using the second cost function.

```{r}
# Run NMF (R=20)
outcome_5=NMF_2.function(gray_image_mat,20,5000,0.01)
# Get W and H.
W_image=outcome_5$a
H_image=outcome_5$b
# Get NMF approximation and transform to image.
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)

# Run NMF (R=40)
outcome_6=NMF_2.function(gray_image_mat,40,5000,0.01)
# Get W and H.
W_image=outcome_6$a
H_image=outcome_6$b
# Get NMF approximation and transform to image.
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)

# Run NMF (R=80)
outcome_7=NMF_2.function(gray_image_mat,80,5000,0.01)
# Get W and H.
W_image=outcome_7$a
H_image=outcome_7$b
# Get NMF approximation and transform to image.
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)

# Run NMF (R=160)
outcome_8=NMF_2.function(gray_image_mat,160,5000,0.01)
# Get W and H.
W_image=outcome_8$a
H_image=outcome_8$b
# Get NMF approximation and transform to image.
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)
```







