---
title: "image compression"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,collapes = TRUE,message = FALSE)
```

# Load the image and print out the original image.

```{r}
rm(list=ls())
library(NMF)
library(imager)
rgb_image <- load.image("https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Raffaello_Sanzio_-_Madonna_del_Cardellino_-_Google_Art_Project.jpg/549px-Raffaello_Sanzio_-_Madonna_del_Cardellino_-_Google_Art_Project.jpg")
plot(rgb_image, axes = FALSE)
```

# Convert the image into a gray-scale format, which reduces its spectrum to a single channel.

```{r}
gray_image <- grayscale(rgb_image)
plot(gray_image, axes = FALSE)
```

# The result of the NMF package (when R=20).

```{r}
gray_image_mat <- as.matrix(gray_image)
nmf_models_lee <- nmf(gray_image_mat, rank = 20, method = "lee", seed = 1234)
plot(as.cimg(fitted(nmf_models_lee)),axes = FALSE)
```

# The result of basic coding (when R=20).

```{r}
NMF_1.function = function(V,R,iter,err){
  N = nrow(V)
  M = ncol(V)
  W = matrix(nrow = N, ncol = R) #Set W with N rows and R columns
  H = matrix(nrow = R, ncol = M) #Set H with R rows and M columns
  W = matrix(runif(N*R, min=0, max=max(V)), nrow=N)#Aviod for loops to improve calculation speed.
  #for (n in 1:N){
    #for (r in 1:R){
      #W[n,r] = runif(1,min=0,max=max(V))
    #}
  #}#initialise W
  H = matrix(runif(R*M, min=0, max=max(V)), nrow=R)#Aviod for loops to improve calculation speed.
  #for (r in 1:R){
    #for (m in 1:M){
      #H[r,m] = runif(1,min=0,max=max(V))
    #}
  #}#initialise W
  W_1=W
  H_1=H
  for (k in 1:iter){
    A=V%*%t(H_1)
    B=W_1%*%H_1%*%t(H_1)
    C=t(W_1)%*%V
    D=t(W_1)%*%W_1%*%H_1
    for (n in 1:N){
      for (r in 1:R){
        W[n,r] = W_1[n,r]*A[n,r]/B[n,r]
      }
    }
    for (r in 1:R){
      for (m in 1:M){
        H[r,m] = H_1[r,m]*C[r,m]/D[r,m]
      }
    }
    W_1=W
    H_1=H
    E=W%*%H-V
    distance=sum(E^2)
    #sum=0
    #for (n in 1:N){
      #for (m in 1:M){
        #sum=sum+(E[n,m]-V[n,m])^2
      #}
    #}
    if (distance<err){
      break
    }
  }
  output=list(a=W,b=H)
  return(output)
}
outcome_1=NMF_1.function(gray_image_mat,20,5000,0.01)
W_image=outcome_1$a
H_image=outcome_1$b
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)
```

# The result of the NMF package (when R=40).

```{r}
gray_image_mat <- as.matrix(gray_image)
nmf_models_lee <- nmf(gray_image_mat, rank = 40, method = "lee", seed = 1234)
plot(as.cimg(fitted(nmf_models_lee)),axes = FALSE)
```

# The result of basic coding (when R=40).

```{r}
outcome_1=NMF_1.function(gray_image_mat,40,5000,0.01)
W_image=outcome_1$a
H_image=outcome_1$b
V_nmf=W_image%*%H_image
plot(as.cimg(V_nmf),axes = FALSE)
```

