---
title: "Sparse NMF"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,collapes = TRUE,message = FALSE)
```

# Function for FC-NNLS

```{r}
rm(list=ls())
FCNNLS.function = function(C,A){
  nObs = nrow(C)
  lVar = ncol(C)
  pRHS = ncol(A)
  
  #Initialisation
  W = matrix(0, lVar, pRHS)
  iter=0
  maxiter=3*lVar
  
  # Precompute parts of pseudoinverse
  CtC = crossprod(C)
  CtA = crossprod(C,A)
  
  # The initial feasible solution and corresponding passive set
  K = CSSLS.function(CtC, CtA, NULL)
  Pset = K > 0
  K[!Pset] = 0
  D = K
  
  #Find the set of columns that is yet to be optimized
  Fset = which( colSums(Pset) != lVar )
  oitr=0
  
  while (length(Fset)>0){
    oitr=oitr+1
    
    K[,Fset] = CSSLS.function(CtC, CtA[,Fset, drop=FALSE], Pset[,Fset, drop=FALSE])
    # Find any infeasible solutions
		# Put indices of columns with negative variables into set H.
		Hset = Fset[ colSums(K[,Fset, drop=FALSE] < 0) > 0 ]
		# Make infeasible solutions feasible (standard NNLS inner loop)
		if (length(Hset)>0){
		  nHset = length(Hset)
			alpha = matrix(0, lVar, nHset)
			while (nHset>0  && (iter < maxiter)){
			  iter = iter + 1 
				alpha[,1:nHset] = Inf
				#Vc# Find indices of negative variables in passive set
				ij = which( Pset[,Hset, drop=FALSE] & (K[,Hset, drop=FALSE] < 0) , arr.ind=TRUE)			
				i = ij[,1]
				j = ij[,2]
				if ( length(i)==0 ){
				  break	
				}
				hIdx = (j - 1) * lVar + i # convert array indices to indexes relative to a lVar x nHset matrix
				negIdx = (Hset[j] - 1) * lVar + i # convert array indices to index relative to the matrix K (i.e. same row index but col index is stored in Hset)
				
				alpha[hIdx] = D[negIdx] / (D[negIdx] - K[negIdx])				
				alpha.inf <- alpha[,1:nHset, drop=FALSE]
				minIdx = max.col(-t(alpha.inf)) # get the indce of the min of each row
				alphaMin = alpha.inf[minIdx + (0:(nHset-1) * lVar)]
				alpha[,1:nHset] = matrix(alphaMin, lVar, nHset, byrow=TRUE)
				D[,Hset] = D[,Hset, drop=FALSE] - alpha[,1:nHset, drop=FALSE] * (D[,Hset, drop=FALSE]-K[,Hset, drop=FALSE])			
				idx2zero = (Hset - 1) * lVar + minIdx # convert array indices to index relative to the matrix D
				D[idx2zero] = 0
				Pset[idx2zero] = FALSE
				K[, Hset] = CSSLS.function(CtC, CtA[,Hset, drop=FALSE], Pset[,Hset, drop=FALSE])
				# which column of K have at least one negative entry?
				Hset = which( colSums(K < 0) > 0 )
				nHset = length(Hset)
			}
		}
		#Vc# Make sure the solution has converged
		#if iter == maxiter, error('Maximum number iterations exceeded'), end
		# Check solutions for optimality
		W[,Fset] = CtA[,Fset, drop=FALSE] - CtC %*% K[,Fset, drop=FALSE]
		# which columns have all entries non-positive
		Jset = which( colSums( (ifelse(!(Pset[,Fset, drop=FALSE]),1,0) * W[,Fset, drop=FALSE]) > 0 ) == 0 )
		Fset = setdiff(Fset, Fset[Jset])
		if (length(Fset) > 0){
		  #Vc# For non-optimal solutions, add the appropriate variable to Pset						
			# get indice of the maximum in each column
			mxidx = max.col( t(ifelse(!Pset[,Fset, drop=FALSE],1,0) * W[,Fset, drop=FALSE]) )
			Pset[ (Fset - 1) * lVar + mxidx ] = TRUE
			D[,Fset] = K[,Fset, drop=FALSE]
		}
  }
  # return K and Pset
	list(coef=K, Pset=Pset)
}
```

# Function for CSSLS.

```{r}
library(corpcor)
CSSLS.function = function(CtC, CtA, Pset){
  # Solve the set of equations CtA = CtC*K for the variables in set Pset
	# using the fast combinatorial approach
	K = matrix(0, nrow(CtA), ncol(CtA))
	if (is.null(Pset) || length(Pset)==0 || all(Pset)){
	  K = pseudoinverse(CtC) %*% CtA
	}else{
	  lVar = nrow(Pset); pRHS = ncol(Pset)
		codedPset = as.numeric(2.^(seq(lVar-1,0,-1)) %*% Pset)
		sortedPset = sort(codedPset)
		sortedEset = order(codedPset)
		breaks = diff(sortedPset)
		breakIdx = c(0, which(breaks > 0 ), pRHS)
		for(k in seq(1,length(breakIdx)-1)){
		  cols2solve = sortedEset[ seq(breakIdx[k]+1, breakIdx[k+1])]
			vars = Pset[,sortedEset[breakIdx[k]+1]]
			K[vars,cols2solve] <-  pseudoinverse(CtC[vars,vars, drop=FALSE]) %*% CtA[vars,cols2solve, drop=FALSE]
		}
	}
	# return K
	K
}
```

#Function for SNMF/L.

```{r}
sparse_L = function(V,R,max,err,eta,alpha){
   M = nrow(V)
   N = ncol(V)
   H = matrix(nrow = R, ncol = M) #Set H with R rows and M columns
   #initialise H
   H = matrix(runif(R*N, min=0, max=max(V)), nrow=R)#Aviod for loops to improve calculation speed.
   NMF_appr = matrix(0,M,N)
   
   j = 1
   E = err+1
   while(j<=max & E>err){
     j = j+1
     
     #First iterative step.
     H_ANLS = rbind(t(H), matrix(sqrt(alpha),1,R))
     V_ANLS_1 = rbind(t(V),matrix(0,1,M))
     W_T = FCNNLS.function(H_ANLS,V_ANLS_1)$coef
     W = t(W_T)
     
     #Second iterative step.
     I = matrix(sqrt(eta),R,R)
     W_ANLS = rbind(W,I)
     O = matrix(0,R,N)
     V_ANLS_2 = rbind(V,O)
     H = FCNNLS.function(W_ANLS,V_ANLS_2)$coef
     
     #Stop when E is smaller than err.
     E = sum((NMF_appr - W%*%H)^2)
     NMF_appr = W%*%H
   }
   
   output=list(a=W,b=H)
   return(output)
}
```

# Load the 72 images and print out the selected 9 images.

```{r}
library(imager)

#Load the first image
F_image <- load.image("C:/UCD/master/3/data/11/1.jpg")
#Transform to grayscale
F_gray <- grayscale(F_image)
plot(F_gray, axes = FALSE)

#Tansform to vector
F_mat <- as.matrix(F_gray)
V_F_1 <- as.vector(F_mat)

for(i in 2:72){
  #Load the rest images
  path <- paste("C:/UCD/master/3/data/11/", i, ".jpg", sep = "")
  imag <- load.image(file = path)
  gray <- grayscale(imag)
  
  #Transform to vector and combine the vectors as a big matrix
  imag_mat <- as.matrix(gray)
  imag_vec <- as.vector(imag_mat)
  V_F <- cbind(V_F_1, imag_vec)
  V_F_1 <- V_F
}

#Print out the 9 selected images. 
sel=c(3,6,20,21,26,36,40,45,52,55,65,71)
for(i in sel){
  path <- paste("C:/UCD/master/3/data/11/", i, ".jpg", sep = "")
  imag <- load.image(file = path)
  gray <- grayscale(imag)
  plot(gray, axes=FALSE)
}
```

# SNMF/L, eta = 0.1, alpha = 1

```{r}
#Run SNMF/L
result = sparse_L(V_F,24,10000,0.1,0.1,1)
W_re = result$a
H_re = result$b
V_re = W_re%*%H_re

#basic images
for(i in 1:24){
  matx_bas=matrix(W_re[,i],nrow=100,ncol=124)
  plot(as.cimg(1-matx_bas),axes = FALSE)
}

#Approximation.
for(i in sel){
  appr_mat = matrix(V_re[,i], nrow = 100, ncol = 124)
  plot(as.cimg(appr_mat), axes = FALSE)
}
```


# SNMF/L, eta = 0.1, alpha = 0.5

```{r}
#Run algorithm
result = sparse_L(V_F,24,10000,0.1,0.1,0.5)
W_re = result$a
H_re = result$b
V_re = W_re%*%H_re

#Basic images
for(i in 1:24){
  matx_bas=matrix(W_re[,i],nrow=100,ncol=124)
  plot(as.cimg(1-matx_bas),axes = FALSE)
}

#Approximation
for(i in sel){
  appr_mat = matrix(V_re[,i], nrow = 100, ncol = 124)
  plot(as.cimg(appr_mat), axes = FALSE)
}
```

# SNMF/L, eta = 0.05, alpha = 0.1

```{r}
result = sparse_L(V_F,24,10000,0.1,0.05,0.1)
W_re = result$a
H_re = result$b
V_re = W_re%*%H_re

for(i in 1:24){
  matx_bas=matrix(W_re[,i],nrow=100,ncol=124)
  plot(as.cimg(1-matx_bas),axes = FALSE)
}

for(i in sel){
  appr_mat = matrix(V_re[,i], nrow = 100, ncol = 124)
  plot(as.cimg(appr_mat), axes = FALSE)
}
```






